"""create properties table

Revision ID: 694191c6fdb7
Revises: 
Create Date: 2026-09-15 17:20:45.996110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '694191c6fdb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=False),
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='AVAILABLE', nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('size', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("listing_type IN ('FOR_SALE', 'FOR_RENT')", name='ck_properties_listing_type'),
    sa.CheckConstraint("status IN ('AVAILABLE', 'SOLD', 'RENTED', 'UNAVAILABLE')", name='ck_properties_status'),
    sa.CheckConstraint('bathrooms IS NULL OR bathrooms >= 0', name='ck_properties_bathrooms_nonnegative'),
    sa.CheckConstraint('bedrooms IS NULL OR bedrooms >= 0', name='ck_properties_bedrooms_nonnegative'),
    sa.CheckConstraint('price >= 0', name='ck_properties_price_nonnegative'),
    sa.CheckConstraint('size IS NULL OR size >= 0', name='ck_properties_size_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_listing_type'), 'properties', ['listing_type'], unique=False)
    op.create_index(op.f('ix_properties_location'), 'properties', ['location'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_slug'), 'properties', ['slug'], unique=True)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_slug'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_location'), table_name='properties')
    op.drop_index(op.f('ix_properties_listing_type'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
