"""create partners table

Revision ID: d5d96e0e6456
Revises: 88cee2e584d9
Create Date: 2026-09-22 20:54:42.603865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d96e0e6456'
down_revision: Union[str, None] = '88cee2e584d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_partners_display_order_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_is_active'), 'partners', ['is_active'], unique=False)
    op.create_index(op.f('ix_partners_name'), 'partners', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partners_name'), table_name='partners')
    op.drop_index(op.f('ix_partners_is_active'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
